### ISSUE TITLE
Concurrency issue when two MREs access the same resource

### ISSUE THREAD

**Issue by willneedit** [Microsoft/mixed-reality-extension-sdk#237] opened 2019-03-04 21:20 UTC
At least one user experienced a reproducible crash when one GLTF object or kit object - just about any resource - is used in two different MREs in the same space.

The MREs don't even need to be enabled from start. Enabling the first of a set of two is okay, but on enabling a second one using the same resources of the first one, the client of the affected user hangs.

- "Reenter space" is not working
- Avatars of latecomers aren't loaded
- MRE processing is completely halted for the user - even MREs which don't share resources don't work anymore
- Client cannot be exited by normal means; "Application stopped responding"

**Comment by willneedit** [comment] 2019-03-11 07:21
New observations:

1. Using the same object several times in a single MRE, which is used a single time in a given space works. Example: The chevrons of the Stargate.
1. Using the same object once in a single MRE, but said MRE being used more than once in a given space triggers the hang. Example: The sliding door I have in one of my worlds, used in several locations.
1. Activating a previously deactivated MRE, which tries to spawn an already used object, triggers this bug as well.
1. Two users affected so far (out of maybe ten)

My current theory is that when a new asset is added to the resources, either by loading using Actor.CreateFromLibrary(), Actor.CreateGLTF() or in lieu of actor synchronization and it is already there because another MRE already loaded it, the function or thread silently exits without giving a notification to its caller, and said caller would stop working and endlessly hang, waiting for a confirmation that never comes.

Why it affects only several people and not everyone eludes me.

**Comment by willneedit** [comment] 2019-03-11 08:53
Perhaps the commonality between two crashing MRE's are not objects, but assets.

A double instance of the GLTF loader MRE, loading the same model leads to a crash, and a multiple instance of the Blast Door, loading the same sound effect leads to a crash.

For testing purposes, I'll remove the sound and have the Blast Door MRE just use the kit objects to see if my theory pans out.

**Comment by willneedit** [comment] 2019-03-11 21:16
Removing the sound didn't fix things. So it definitely concerns objects in general and not just "loose" items downloaded using an URL.

**Comment by stevenvergenz** [comment] 2019-03-13 21:32
I'm still unable to reproduce this bug, but I've changed the way the asset cache is used for glTFs in the linked PR, maybe it'll fix it for you?

**Comment by willneedit** [comment] 2019-03-14 07:30
I'll have to try. Thing is, it doesn't affect just glTF's, but other kinds of assets as well, but only if they're loaded from _different_ MRE's in the same space... and it only affects specific users, for some reason.

Though, even if the PR fixes things just for glTF's it helps tracking down the root cause of this issue.

**Comment by willneedit** [comment] 2019-03-15 18:50
Hmmm.... Debugging with mixed-reality-extensions-unity remains a bit inconclusive. I've traced the call down to MRETestBed/ResourceFactory.cs::CreateFromLibrary, which is a stub in lieu of retrieving the 'real' kit object.

If the live code in place of this unconditionally tries to retrieve the kit object from the web into the asset storage, maybe because the second MRE doesn't know it's already loaded by the first one, it could account for the problem.

Taking a wild guess here. As for assets retrieved at runtime - is there a room-scoped bookkeeping to avoid double retrieval, or is it only scoped to contexts?

**Comment by willneedit** [comment] 2019-03-18 06:53
Built a workaround.

In essence, I'm multiplexing all the different apps into what shows up as a single MRE inside the World Editor. The definitions of the "sub MREs" are places in a JSON file which is referenced and loaded at runtime, but that's beside the point.

Major difference is that the same apps which led to a crash when incorporated separately using different contexts work fine when they're subsumed into a single context.

**Comment by stevenvergenz** [comment] 2019-03-18 17:46
This update just went out to Altspace, see if you can still repro this bug. I'm closing this issue for now, but please re-open it if it's not fixed. Thanks.

**Closed by stevenvergenz** 2019-03-18 17:46 UTC
