### ISSUE TITLE
[0.12.n regression] Grab test

### ISSUE THREAD

**Issue by eanders-MS** [microsoft/mixed-reality-extension-sdk#397] opened 2019-07-23 16:02 UTC
Test: 2 player, PC and Quest
Quest: non-authoritative peer
PC: authoritative peer

Grabber: non-authoritative, on Quest:
    - Grabbed box synced successfully.
    - Grabbed monkey worked fine on grabber's device, but did not sync.
    - 2nd attempt to grab box: did not sync.
 Grabber: authoritative peer, on PC:
    - Grabbed objects synced successfully, repeatedly.
 Grabber: non-authoritative, on Quest:
    - Same as before: 1st grab synced. Subsequent grabs failed to sync.

**Comment by eanders-MS** [comment] 2019-07-24 22:28
Update: Appears that 6-dof grab is not synced (Altspace-specific).

**Comment by stevenvergenz** [comment] 2019-07-26 21:10
I've reproduced this bug, but had a different conclusion: non-authoritative grabber updates are not sent to late joiners. Tested with authoritative testbed and Altspace, taking turns grabbing from one or the other then rejoining in Altspace.

**Comment by stevenvergenz** [comment] 2019-07-26 22:52
Based on my above test results, I think there's more than one bug here. One is that non-authoritative peers' updates don't get saved in the session, because those are never reflected in late joiner states. Another is that 6DOF Altspace does not send updates for some reason.

**Comment by eanders-MS** [comment] 2019-07-29 15:40
Thanks @stevenvergenz! How were you determining Receiver -> Session?

**Comment by stevenvergenz** [comment] 2019-08-01 03:10
@eanders-MS Session sync determined by late joiner state.

**Comment by stevenvergenz** [comment] 2019-08-20 22:57
Fixed by #416

**Closed by stevenvergenz** 2019-08-20 22:57 UTC
Labels: bug, regression
